mode: "deployment"

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: otel/opentelemetry-collector
  tag: "0.94.0"
  pullPolicy: IfNotPresent

command:
  name: otelcol
  extraArgs:
    - "--config=/conf/relay.yaml"

resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    memory: 256Mi
    cpu: 250m

configMap:
  create: true
  existingName: ""

config:
  exporters:
    debug: {}
  extensions:
    health_check:
      endpoint: ${env:MY_POD_IP}:13133
  processors:
    batch: {}
    memory_limiter:
      check_interval: 5s
      limit_percentage: 80
      spike_limit_percentage: 25
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:14250
        thrift_http:
          endpoint: ${env:MY_POD_IP}:14268
        thrift_compact:
          endpoint: ${env:MY_POD_IP}:6831
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318
    prometheus:
      config:
        scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
              - targets:
                  - ${env:MY_POD_IP}:8888
    zipkin:
      endpoint: ${env:MY_POD_IP}:9411
  service:
    telemetry:
      metrics:
        readers:
          - pull:
              exporter:
                prometheus:
                  host: ${env:MY_POD_IP}
                  port: 8888
    extensions:
      - health_check
    pipelines:
      logs:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [debug]
      metrics:
        receivers: [otlp, prometheus]
        processors: [memory_limiter, batch]
        exporters: [debug]
      traces:
        receivers: [otlp, jaeger, zipkin]
        processors: [memory_limiter, batch]
        exporters: [debug]

# Remove the ports section here as it's causing an invalid spec error
service:
  enabled: true
  type: ClusterIP

livenessProbe:
  httpGet:
    port: 13133
    path: /

readinessProbe:
  httpGet:
    port: 13133
    path: /

serviceAccount:
  create: true
  name: ""

clusterRole:
  create: false
  name: ""
  clusterRoleBinding:
    name: otel-collector-binding

serviceMonitor:
  enabled: true
  interval: 10s
  scrapeTimeout: 10s
  labels:
    release: prometheus

prometheusRule:
  enabled: false
  labels: {}
  rules: []

# ✅ Fix: Add this podMonitor block
podMonitor:
  enabled: false
  metricsEndpoints:
    - port: metrics
      interval: 10s
      path: /metrics
  extraLabels: {}
