{{- if or (.Values.clusterRole.create) (.Values.presets.kubernetesAttributes.enabled) (.Values.presets.clusterMetrics.enabled) (.Values.presets.kubeletMetrics.enabled) (.Values.presets.kubernetesEvents.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRole.clusterRoleBinding.name | default (include "opentelemetry-collector.fullname" .) }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
  {{- with .Values.clusterRole.binding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.clusterRole.name | default (include "opentelemetry-collector.fullname" .) }}
subjects:
  - kind: ServiceAccount
    name: {{ include "opentelemetry-collector.serviceAccountName" . }}
    namespace: {{ include "opentelemetry-collector.namespace" . }}
{{- end }}
